name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "MLProject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
      
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
      
      # Start MLflow tracking server in background
      - name: Start MLflow tracking server
        run: |
          mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000 &
      
      # Set MLFLOW_TRACKING_URI environment variable and run mlflow project
      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000
        run: |
          mlflow run MLProject --env-manager=local

      # Save models to GitHub Repository
      - name: Save mlruns to repo
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git add mlruns/
          git commit -m "Save mlruns from CI run"
          git push origin master
