name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "MLProject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env Variables
        run: echo $CSV_URL

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Start MLflow tracking server
        run: |
          mlflow server --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000 &

      - name: Run MLflow project
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000
        run: |
          mlflow run MLProject --env-manager=local

      - name: Configure Git and push mlruns to repo
        env:
          GIT_TOKEN: ${{ secrets.TOKEN }}
          GIT_USER: ${{ secrets.USERNAME }}
          GIT_EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config --global user.name "$GIT_USER"
          git config --global user.email "$GIT_EMAIL"
          git remote set-url origin https://x-access-token:$GIT_TOKEN@github.com/${{ github.repository }}

          git add mlruns/
          git diff --cached --quiet || git commit -m "Save mlruns from CI run"
          git push origin master
